### ISSUE TITLE
Cant persist an object to LDAP

### ISSUE THREAD

**Issue by NKPmedia** [ucsf-iam/UcsfLdapOrm#2]
Hello guys,

if I try to persist an object to the ldap I get this error:

> TypeError: Argument 3 passed to Ucsf\LdapOrmBundle\Ldap\LdapEntityManager::ldapUpdate() must be an instance of Ucsf\LdapOrmBundle\Entity\Ldap\LdapEntity, boolean given, called in /home/paul/Dokumente/PHPStrom/ScoTooBo/vendor/ucsf/ldaporm-bundle/Ucsf/LdapOrmBundle/Ldap/LdapEntityManager.php on line 408

I think I get this error because if there is no existing entry, `$result` is an emty array.
Then `$originalEntity` becomes false (because of the reset) and `count(false)` is 1.

But if I add this line to fix the problem:
`if($originalEntity == false) $originalEntity = null;`

I get this error:

> TypeError: Argument 1 passed to Ucsf\LdapOrmBundle\Ldap\LdapEntityManager::getEntityOperands() must be an instance of Ucsf\LdapOrmBundle\Entity\Ldap\LdapEntity, array given, called in /home/paul/Dokumente/PHPStrom/ScoTooBo/vendor/ucsf/ldaporm-bundle/Ucsf/LdapOrmBundle/Ldap/LdapEntityManager.php on line 515

I hope you can fix the problems :)

**Comment by jasongabler** [comment]
Hello NKPmedia,

This is somewhat amusing as ldapPersist() has probably been broken for some time because I never use this bundle for persisting new entries to LDAP.  (My workplace's directory is populated from wholly different software that I do not work with.)  LdapUpdate(), which I use often, has for sometime been sending LdapEntitys to getEntityOperands().   ldapPersist() just needs to be brought up to date in a more thorough manner than your initial attempt, which was a valid beginning.

If I find the time, I will fix it, though my work is not demanding it. So, no guarantees for a timeframe. However, if you go ahead and fix it I will gladly accept a pull request.

Are you using 2.x or 3.x?

Jason

**Comment by NKPmedia** [comment]
Hey Jason,

Im using Symfony 3 at the moment. I think I will try to fix the problem, because I need this function for my project, but I don't know if my quality is good enough for you.

We will see...


Paul
